language: php
php:
  - 5.6
  - hhvm
matrix:
  allow_failures:
  - php: hhvm
env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
  - MAGENTO_VERSION=magento-mirror-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.9.2.4 
  - MAGENTO_VERSION=magento-mirror-1.9.3.1
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - dominic.watts@hotmail.co.uk
    on_success: always
    on_failure: always